FROM jenkins/jenkins:lts

USER root

RUN apt-get update && \
    apt-get install -y docker.io make g++ curl && \
    groupmod -g 999 docker || groupadd -g 999 docker && \
    usermod -aG 999 jenkins && \
    apt-get clean

USER jenkins